opt_in_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - indentation_width

trailing_whitespace:
  ignores_empty_lines: true

indentation_width:
  include_comments: false

identifier_name:
  excluded:
    - id
    - sm
    - md
    - lg
    - xs
    - xl
    - ai
    - x
    - y
    - up
    - sp

# paths to ignore during linting. Takes precedence over `included`.
excluded:                                                                                                                                    
  - Pods                                                                                                                                     
  - "Backpack\ Screenshot/"                                                                                                                  
  - ../Backpack-SwiftUI/Button/Classes/BPKButton.swift                                                                                       
  - ../Backpack-SwiftUI/Text/Classes/BPKText.swift                                                                                           
  - ../Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift                                                                                       
  - ../Backpack-SwiftUI/StarRating/Classes/BPKHotelStarRating.swift                                                                          
  - ../Backpack-SwiftUI/CardButton/Classes/BPKSaveCardButton.swift
  # exclude tests                                                                           
  - ../Backpack-SwiftUI/Tests
  - ../Backpack/Tests
  - ../Backpack-Common/Tests
  # exclude colours      
  - ../Backpack-SwiftUI/Color/Classes/Generated/BPKInternalColors.swift                                                                      
  - ../Backpack/Color/Classes/Generated/BPKInternalColors.swift
  - ../Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  - ../Backpack-SwiftUI/Button/Classes/BPKButtonColorSet.swift
  - ../Backpack-Common/Configuration/Classes/BPKConfiguration.swift
  # exclude example app                                                                                                        
  - Backpack/
  # ... other exclusions ...                                                                                                                 
  - "**/*_Previews.swift"  
included:
  - ../Backpack
  - ../Backpack-SwiftUI
  - ../Backpack-Common

custom_rules:
  # These custom rules came from https://github.com/Skyscanner/backpack-swiftlint-rules/blob/main/src/BackpackSwiftLintRules.yml
  # They will need to be updated manually when changes are made.

  # Component rules

  bpk_text:
    name: "Use BPKText instead of Text"
    regex: "(?<!BPK)(?<!accessibilityLabel\\()Text\\(" 
    message: "Use BPKText instead of Text. Example: BPKText(\"text\", style: .bodyDefault)"
    severity: warning

  backpack_text_uikit:
    name: "Prefer Backpack Text over UIKit"
    regex: "\\bUILabel\\b"
    message: "Use BPKText from Backpack-SwiftUI instead of UILabel"
    severity: warning

  bpk_button:                                                                                                                                  
    name: "Use BPKButton instead of Button"                                                                                                    
    regex: "(?<![A-Za-z])Button\\("                                                                                                            
    message: "Use BPKButton instead of Button. Example: BPKButton(\"Action\", style: .primary) { }"                                            
    severity: warning    

  bpk_button_uikit:                                                                                                                            
    name: "Prefer BPKObjcUIKitButton to UIButton"                                                                                              
    regex: "UIButton\\("                                                                                                                       
    message: "Use BPKButton instead of UIButton."                                                                                              
    severity: warning

  bpk_label:
    name: "Prefer BPKLabel to UILabel"
    regex: "(UILabel)\\("
    message: "Use BPKLabel instead of UILabel."
    severity: warning # default is warning

  bpk_progress:
    name: "Prefer BPKProgressBar to UIProgressView"
    regex: "(UIProgressView)\\("
    message: "Use BPKProgressBar instead of UIProgressView."
    severity: warning # default is warning

  bpk_spinner:
    name: "Prefer BPKSpinner to UIActivityIndicatorView"
    regex: "(UIActivityIndicatorView)\\("
    message: "Use BPKSpinner instead of UIActivityIndicatorView."
    severity: warning # default is warning

  bpk_switch:
    name: "Use BPKSwitch instead of Toggle"
    regex: "\\bToggle\\("
    message: "Use BPKSwitch instead of Toggle. Example: BPKSwitch(isOn: $value)"
    severity: warning

  bpk_switch_uikit:
    name: "Prefer BPKSwitch to UISwitch"
    regex: "(UISwitch)\\("
    message: "Use BPKSwitch instead of UISwitch."
    severity: warning # default is warning

  bpk_text_field:
    name: "Prefer BPKTextField to UITextField"
    regex: "(UITextField)\\("
    message: "Use BPKTextField instead of UITextField."
    severity: warning # default is warning

  bpk_text_view:
    name: "Prefer BPKTextView to UITextView"
    regex: "(UITextView)\\("
    message: "Use BPKTextView instead of UITextView."
    severity: warning # default is warning
    # Try it out at https://regex101.com/r/F8sAgX/1

  bpk_spacing:                                                                                                                                 
    name: "Prefer BPKSpacing to hard-coded numbers"                                                                                            
    regex: '(?:padding|spacing|minLength|frame\s*\([^)]*(?:width|height))\s*:\s*(?!BPKSpacing)(?!0(?:\.0+)?\b)([0-9]+(?:\.[0-9]+)?)'           
    message: "Use BPKSpacing tokens instead of hard-coded numbers. Available: .none, .sm (4), .md (8), .base (16), .lg (24), .xl (32), .xxl (40), .xxxl (64), .xxxxl (96)"                                                                                                               
    severity: warning     

  bpk_bottomsheet:
    name: "Prefer BPKBottomsheet to sheet modifier"
    regex: "\\.sheet\\("
    message: "Use BPKBottomsheet instead of sheet modifier."
    severity: warning # default is warning  

  # typography?  

  # Size token rules

  bpk_use_size_token:
    name: "Prefer Backpack tokens to hard-coded numbers"
    regex: "(?:(?:cornerRadius|spacing)\\s*=\\s*(?:[0-9\\.]+\\s*\\*\\s*)*([1-9]+(?:\\.[0-9]+)?)$|constrain.*?constant\\s*:\\s*(?:[0-9\\.]+\\s*\\*\\s*)*([1-9]+(?:\\.[0-9]+)?)\\s*\\))"
    message: "Use a size or radius token from Backpack instead of a hard-coded number."
    severity: warning # default is warning
    # Try it out at https://regex101.com/r/a2znCq/17

  # Colour token rules

  bpk_use_colour_token:
    name: "Prefer Backpack colour tokens to UIColors"
    regex: "(?:(?:Color|color)\\s+=\\s+(UIColor)|Variant\\s*\\:\\s*(UIColor))"
    message: "Use a colour token from Backpack instead of a UIColor."
    severity: warning # default is warning
    # Try it out at https://regex101.com/r/3NOwYr/13

  system_colors:
    name: "Use Backpack color tokens"
    regex: "Color\\.(red|blue|green|yellow|orange|purple|black|white|gray)\\b"
    message: "Use Backpack color token instead of system colors. Example: .textPrimaryColor, .canvasColor"
    severity: warning

  # Regex for numerical/hex value for colors                                                                                                 
                                                                                                                                               
  hex_color_literal:                                                                                                                         
    name: "Use Backpack color tokens instead of hex literals"                                                                                
    regex: '(?:#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{3}|0x[0-9A-Fa-f]{6})'                                                                            
    message: "Use Backpack color tokens instead of hex color literals. Example: .canvasColor, .textPrimaryColor"                             
    severity: warning                                                                                                                        
                                                                                                                                              
  rgb_color_values:                                                                                                                          
    name: "Use Backpack color tokens instead of RGB values"                                                                                  
    regex: '(?:Color|UIColor)\s*\(\s*red:\s*[0-9.]'                                                                                          
    message: "Use Backpack color tokens instead of RGB/numeric color values. Example: .canvasColor, .textPrimaryColor"                       
    severity: warning 

  uicolor_usage:
    name: "Use Backpack color tokens instead of UIColor"
    regex: "\\bUIColor\\.(red|blue|green|yellow|orange|purple|black|white|gray|clear|systemBackground)\\b"
    message: "Use Backpack color tokens (Color extension). Example: .canvasColor, .textPrimaryColor"
    severity: warning

  # SF Symbol replacements
  sf_symbol_star:
    name: "Use BPKHotelStarRating instead of SF Symbols"
    regex: "Image\\(systemName:\\s*\"star"
    message: "Use BPKHotelStarRating or BPKStarRating instead of SF Symbols stars"
    severity: warning

  sf_symbol_heart:
    name: "Use BPKSaveCardButton instead of SF Symbols"
    regex: "Image\\(systemName:\\s*\"heart"
    message: "Use BPKSaveCardButton instead of SF Symbols heart"
    severity: warning

reporter: "xcode"
