parent_config: ../.swiftlint-custom-rules.yml

opt_in_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - indentation_width

trailing_whitespace:
  ignores_empty_lines: true

indentation_width:
  include_comments: false

identifier_name:
  excluded:
    - id
    - sm
    - md
    - lg
    - xs
    - xl
    - ai
    - x
    - y
    - up
    - sp

# paths to ignore during linting. Takes precedence over `included`.
excluded:                                                                                                                                    
  - Pods                                                                                                                                     
  - "Backpack\ Screenshot/"                                                                                                                  
  - ../Backpack-SwiftUI/Button/Classes/BPKButton.swift                                                                                       
  - ../Backpack-SwiftUI/Text/Classes/BPKText.swift                                                                                           
  - ../Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift                                                                                       
  - ../Backpack-SwiftUI/StarRating/Classes/BPKHotelStarRating.swift                                                                          
  - ../Backpack-SwiftUI/CardButton/Classes/BPKSaveCardButton.swift
  # exclude tests                                                                           
  - ../Backpack-SwiftUI/Tests
  - ../Backpack/Tests
  - ../Backpack-Common/Tests
  # exclude colours      
  - ../Backpack-SwiftUI/Color/Classes/Generated/BPKInternalColors.swift                                                                      
  - ../Backpack/Color/Classes/Generated/BPKInternalColors.swift
  - ../Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
  - ../Backpack-SwiftUI/Button/Classes/BPKButtonColorSet.swift
  - ../Backpack-Common/Configuration/Classes/BPKConfiguration.swift
  # exclude example app                                                                                                        
  - Backpack/
  # ... other exclusions ...                                                                                                                 
  - "**/*_Previews.swift"  
included:
  - ../Backpack
  - ../Backpack-SwiftUI
  - ../Backpack-Common

reporter: "xcode"
