parent_config: ../.backpack-ios-rules.yml

opt_in_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - indentation_width

trailing_whitespace:
  ignores_empty_lines: true

indentation_width:
  include_comments: false

identifier_name:
  excluded:
    - id
    - sm
    - md
    - lg
    - xs
    - xl
    - ai
    - x
    - y
    - up
    - sp

# paths to ignore during linting. Takes precedence over `included`.
excluded:                                                                                                                                    
    - Pods                                                                                                                                     
    - "Backpack\ Screenshot/"                                                                                                                  
    # Exclude all BPK component implementations                                                                                                
    - ../Backpack-SwiftUI/*/Classes                                                                                                            
    - ../Backpack/*/Classes                                                                                                                    
    # Exclude tests                                                                                                                            
    - ../Backpack-SwiftUI/Tests                                                                                                                
    - ../Backpack/Tests                                                                                                                        
    - ../Backpack-Common/Tests                                                                                                                 
    # Exclude colors                                                                                                                           
    - ../Backpack-SwiftUI/Color/Classes/Generated                                                                                              
    - ../Backpack/Color/Classes/Generated                                                                                                      
    - ../Backpack-Common/Configuration/Classes/BPKConfiguration.swift                                                                          
    # Exclude example app                                                                                                                      
    - Backpack/  
included:
  - ../Backpack
  - ../Backpack-SwiftUI
  - ../Backpack-Common

reporter: "xcode"
