source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'
use_frameworks!
ensure_bundler! '> 2.0'

install! 'cocoapods', disable_input_output_paths: true

target 'Backpack-Native' do
  pod 'Backpack', :path => '../', :testspecs => ['UnitTests', 'SnapshotTests']
  pod 'Backpack-SwiftUI', :path => '../', :testspecs => ['Tests']
  pod 'Backpack-Fonts', :path => '../Backpack-Fonts'
  pod 'Backpack-Common', :path => '../'
  pod 'SwiftLint', '~> 0.43.1'
  pod 'AppCenter', '~> 4.2.0'
  pod 'AppCenter/Distribute', '~> 4.2.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end

  puts 'Removing static analyzer support'
  installer.pods_project.targets.each do |target|
      if target.name == "FSCalendar"
          target.build_configurations.each do |config|
              config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
          end
      end

      # Fix SwiftUI previews
      # https://github.com/CocoaPods/CocoaPods/issues/9275#issuecomment-923709000
      if target.name == 'Backpack-SwiftUI'
        target.build_configurations.each do |config|
        if config.name == 'Debug'
            config.build_settings["LD_RUNPATH_SEARCH_PATHS"] += " $(FRAMEWORK_SEARCH_PATHS)"
        end
      end
    end
  end
end
