# A list of devices you want to take the screenshots from
devices(["iPhone SE (3rd generation)"])

# The ios version to take the screenshots from
ios_version("16.4")

# The languages to take the screenshots in
languages(["en-US"])

# The name of the scheme which contains the UI Tests
scheme("Backpack Screenshot")

# Where should the resulting screenshots be stored?
output_directory("../screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
