# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# $MAIN_STAGE is used to selectively run only certain steps on the
# latest iOS version. For example snapshot tests are only ran for the
# latest version.
osx_image: xcode10
language: objective-c
cache:
  cocoapods: true
  bundler: true
  directories:
    - node_modules
matrix:
  include:
    - osx_image: xcode10
      env: BUILD_SDK=iphonesimulator12.0 DESTINATION="OS=12.0,platform=iOS Simulator,name=iPhone 8" FULL_TESTS="true" MAIN_STAGE="true"
    - osx_image: xcode9.4
      env: BUILD_SDK=iphonesimulator11.4 DESTINATION="OS=11.4,platform=iOS Simulator,name=iPhone 8" FULL_TESTS="false" MAIN_STAGE="false"
    - osx_image: xcode9.4
      env: BUILD_SDK=iphonesimulator11.4 DESTINATION="OS=10.3.1,platform=iOS Simulator,name=iPhone 7" FULL_TESTS="false" MAIN_STAGE="false"
before_install:
  - sudo sntp -sS time.apple.com
  - brew install clang-format
  - nvm install
  - nvm use
  - 'if [[ "$MAIN_STAGE" = true ]]; then npm install -g greenkeeper-lockfile@1; fi'
install:
  - npm install
  - bundle install
  - bundle exec pod repo update
  - (cd Example && bundle exec pod install)
before_script: 'if [[ "$MAIN_STAGE" = true ]]; then greenkeeper-lockfile-update; fi'
script:
  - npm run build
  - 'if [[ "$MAIN_STAGE" = true ]]; then ./scripts/check-pristine-state package-lock.json; fi'
  - 'if [[ "$MAIN_STAGE" = true ]]; then Example/Pods/SwiftLint/swiftlint lint --strict --config Example/.swiftlint.yml; fi'
  - 'if [[ "$MAIN_STAGE" = true && ! -n "$TRAVIS_TAG" ]]; then ./scripts/build-docs-ci && rm -rf docs; fi'
  - 'if [[ "$MAIN_STAGE" = true && -n "$TRAVIS_TAG" ]]; then ./scripts/build-docs-ci $TRAVIS_TAG; fi'
  - (cd Example && bundle exec rake ci)
after_script: 'if [[ "$MAIN_STAGE" = true ]]; then greenkeeper-lockfile-upload; fi'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $IOS_DOCS_DEPLOY_TOKEN
  on:
    tags: true
    all_branches: true
    condition: "$MAIN_STAGE = true"
  local_dir: docs/
  skip_cleanup: true
  detect_encoding: true
  repo: backpack/ios
  target-branch: master
  verbose: true
  keep-history: true

env:
  global:
    - secure: qKO1dhfy5WsvI1bIeTLA+V89DoYd2HzbNJ72mK71FF/vEewfDOyxDA7TbBc4ogwpKZv8YZdIahDZe+BdR12ICm5h5J3sV7uqVAm1TnJr79k+G/YfrNtevAxfv1Ja9oYed7brqz8MkxtzM4An8o9ncmV1T9fDxJExyDvWGF6YkN46QXuz7wBg7jrRZ/P/WAvrdYXtisXjhMQjWQOzgF/6DKhexGHirrE/IE26AmJA3akSbYZn1sQSxQXyzX4cfabewHODEjxtHWWQr97yYvmKY2bCRbFN+IxPY7/wFCjKv9IKePKs4tajlwsj7gknxJC7PqdJOqjSGSFvbm98WJ66dFKzZbQpYaGz3v87w6EmcQp7xaKjmcqThDGHtKSPLtppKedFki0wAkZSQyE+vnqVV2eCpY8JLqweoPIaXw3eHDU7Q/4xqSXzb7sMCEu3l4W2DQ/ZanRQkQwlwslleAK+QHyFfnOkGYJWr2EoB3kLqIbgyvEn8+LOH6GhFOR5Z9Rh2REAqCXgWCEMRaIycDigJS+9OCxZlpP740EtqCQsASKx/cEoz8lbEGA6bQWGyjbGE5XsSDx6gMUszIDMK+e48KqKatLosMkPDM1hyGVwxyRf8bh7Ske8NIfJ0Whw667Qo/5UWMtC9OiG9NZ+iSLbur9Gtq/X7MEZDaM6Y5BnB2w=
