name: Setup SwiftPM Workspace
description: Select Xcode and prepare the SwiftPM Xcode workspace

inputs:
  xcode-path:
    description: Path to the Xcode app to select
    required: false
    default: /Applications/Xcode_16.2.app
  workspace-file:
    description: Relative path to the workspace data file
    required: false
    default: .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata

runs:
  using: composite
  steps:
    - name: Select Xcode
      shell: bash
      run: sudo xcode-select --switch "${{ inputs.xcode-path }}"

    - name: Prepare SwiftPM Xcode workspace
      shell: bash
      run: |
        set -eo pipefail
        workspace_file="${{ inputs.workspace-file }}"
        mkdir -p "$(dirname "$workspace_file")"
        cat <<'EOF' > "$workspace_file"
        <?xml version="1.0" encoding="UTF-8"?>
        <Workspace
           version = "1.0">
           <FileRef
              location = "self:">
           </FileRef>
        </Workspace>
        EOF
