#!/usr/bin/env node

const {
    promisify
} = require("util");
const {
    exec
} = require('child_process');
const execAsync = promisify(exec);

const command = 'git status --porcelain | awk \'{print $2}\'';
const [node, path, ...filesToIgnore] = process.argv;

const init = async () => {
    const { stdout } = await execAsync(command, {
        cwd: `${__dirname}/../`
    });
    const changedFiles = stdout
        .trim()
        .split("\n")
        .filter(isNotInList(filesToIgnore))
        .filter(exists);

    if (changedFiles.length) {
        console.log(`😰  Git shows some files have been changed (ignoring ${filesToIgnore.join(",")}). Changed files: ${changedFiles.join(",")}`);
        process.exit(1);
    }
}

const exists = item => !!item

const isNotInList = list => list.indexOf(item) === -1

init();
