#!/bin/bash
set -e

EXAMPLE_WORKSPACE="Example/Backpack.xcworkspace"
SWIFT=${SWIFT:-'5.0'}
BUILD_SDK=${BUILD_SDK:-'iphonesimulator15.2'}
DESTINATION=${DESTINATION:-"platform=iOS Simulator,name=iPhone 8"}

function analyze() {
    xcodebuild analyze \
        -workspace $EXAMPLE_WORKSPACE \
        -scheme "$1" \
        SWIFT_VERSION=$SWIFT \
        -sdk $BUILD_SDK \
        -destination "$(echo $DESTINATION)" \
        ONLY_ACTIVE_ARCH=YES 2>&1 |
        xcpretty
}

function runTests() {
    xcodebuild test \
        -enableCodeCoverage YES \
        -workspace $EXAMPLE_WORKSPACE \
        -scheme "$1" \
        SWIFT_VERSION=$SWIFT \
        -sdk $BUILD_SDK \
        -destination "$(echo $DESTINATION)" \
        ONLY_ACTIVE_ARCH=YES 2>&1
}

function check_modules() {
    if [ $2 == "test" ]; then
        if [ $1 == "uikit" ]; then
            runTests "Backpack-Snapshot-Tests"
            runTests "Backpack-Unit-Tests"

        elif [ $1 == "uitests" ]; then
            runTests "Backpack-UI-Tests"

        elif [ $1 == "swiftui" ]; then
            runTests "Backpack SwiftUI"
        fi
    elif [ $2 == "analysis" ]; then
        if [ $1 == "uikit" ]; then
            analyze "Backpack Native"

        elif [ $1 == "swiftui" ]; then
            analyze "Backpack SwiftUI"

        elif [ $1 == "common" ]; then
            analyze "Backpack-Common"
        fi
    fi
}

if [ $# -lt 2 ]; then
    echo "No arguments provided. Running all tests."
    check_modules "uikit" "test"
    check_modules "swiftui" "test"
    check_modules "common" "test"
    check_modules "uitests" "test"
else
    check_modules $1 $2
fi
