#!/usr/bin/env node

const fs = require('fs');

const lines = fs.readFileSync('Backpack/Backpack.h', 'utf8').split('\n');
const headers = lines
    .filter(line => line.startsWith('#import'))
    .map(line => line.replace('#import "', ''))
    .map(line => line.replace('.h"', ''))
    .map(line => `#import \"${line}/Classes/${line}.h\"`)
    .join('\n');

fs.writeFileSync('Backpack/BackpackDocHeaders.h', headers);
