#!/bin/bash

# This script clones the internal Backpack Fonts repo and adds the fonts to the project resources folder.
# Once this is done, the fonts must be added to XCode by right-clicking on "Example for Backpack > Resources" and selecting "Add files..."

mkdir -p bpk-fonts-tmp
cd bpk-fonts-tmp
git init
git remote add origin git@github.skyscannertools.net:backpack/bpk-fonts.git
git config core.sparsecheckout true
echo "iOS" >> .git/info/sparse-checkout
git pull --depth=1 origin main
cd ..
mkdir -p ./Example/Backpack/Resources/
cp ./bpk-fonts-tmp/iOS/SkyscannerRelativeiOS* ./Example/Backpack/Resources/
rm -rf bpk-fonts-tmp
