#!/bin/bash

function checkPristine() {
    if [ -n "$(git status --porcelain)" ]; then
        echo "$1"
        exit 1
    fi
}

echo "Checking that the working tree is clean"
checkPristine "You have uncommited changes. Please commit or stash them."

brew install clang-format@14
find ./Backpack -name "*.[hm]" -exec clang-format -i {} \+ 

checkPristine "Formatter failed to format some files. Please run 'brew install clang-format@14' and try again."

bundle exec pod lib lint --allow-warnings --skip-tests
