name: _spm-build

on:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}

jobs:
  spm-build:
    name: SwiftPM Build
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup SwiftPM workspace
        uses: ./.github/actions/spm-setup

      - name: Cache iOS Simulator Runtime
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/CoreSimulator/Caches/dyld
          key: ios-simulator-18.0-${{ runner.os }}-${{ runner.arch }}

      - name: Setup iOS Simulator
        run: |
          xcodebuild -downloadPlatform iOS -exportPath ~/Downloads -buildVersion 18.0
          xcrun simctl create 'iPhone 12 mini' 'iPhone 12 mini' iOS18.0

      - name: Build Backpack Swift Package
        env:
          SPM_DESTINATION: platform=iOS Simulator,name=iPhone 12 mini,OS=18.0
        run: |
          set -eo pipefail
          xcodebuild \
            -workspace .swiftpm/xcode/package.xcworkspace \
            -scheme Backpack-Package \
            -destination "$SPM_DESTINATION" \
            -derivedDataPath .derivedData \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            build

      - name: Clean derived data
        if: always()
        run: rm -rf .derivedData
