name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-24.04-2cores-tools-public
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with: # Not including release.yml for the time being.
          inputs: |
            .github/workflows/_build.yml
            .github/workflows/_build-docs.yml
            .github/workflows/_spm-build.yml
            .github/workflows/_spm-test.yml
            .github/workflows/_test.yml
            .github/workflows/label-check.yml
            .github/workflows/main.yml
            .github/workflows/pr.yml
            .github/workflows/snapshot.yml
